### ISSUE TITLE
Skeleton draft of User Home Page

### ISSUE THREAD

**Issue by mkshimod** [radgrad/mvp-mockup-7#7]
Need an outline of what the user home page will look like + what content + where content will go

**Comment by FFAxKenny** [comment]
Done.

**Comment by FFAxKenny** [comment]
For reference

![screenshot_2016-02-23_14-36-25](https://cloud.githubusercontent.com/assets/1109418/13271713/df5140f6-da3a-11e5-8e0b-101cf7461496.png)
